# AUTHOR

### Get all authors
GET http://localhost:9080/library-app/api/authors

### Get author not exist
GET http://localhost:9080/library-app/api/authors/82a84717-c36c-42c1-b69c-c63546d4449c

### Get existing author
GET http://localhost:9080/library-app/api/authors/24a84717-c36c-42c1-b69c-c63546d4449d

### Put new author
PUT http://localhost:9080/library-app/api/authors/a2b8423d-6073-4e57-acbc-f195e6263bb3
Content-Type: application/json

{
  "name": "Andrzej",
  "nationality": "Polish"
}

### Get new author
GET http://localhost:9080/library-app/api/authors/a2b8423d-6073-4e57-acbc-f195e6263bb3

### Patch new author
PATCH http://localhost:9080/library-app/api/authors/a2b8423d-6073-4e57-acbc-f195e6263bb3
Content-Type: application/json

{
  "name": "Jakub",
  "nationality": "Polish"
}

### Delete author
DELETE http://localhost:9080/library-app/api/authors/a2b8423d-6073-4e57-acbc-f195e6263bb3

###

#BOOK

### Get Books by Author
GET http://localhost:9080/library-app/api/authors/24a84717-c36c-42c1-b69c-c63546d4449d/books

### Patch atomic habits
PATCH http://localhost:9080/library-app/api/books/7863889b-51ec-49d8-b7ea-2beff3724c3f
Content-Type: application/json

{
  "title": "Atomic habits updated",
  "releaseDate": "2020-10-11",
  "genre": "TUTORIAL"
}

### Get all books
GET http://localhost:9080/library-app/api/books

### Get book not exist
GET http://localhost:9080/library-app/api/books/7863889b-51ec-49d8-b7ea-2beff3724c3e

### Get existing book
GET http://localhost:9080/library-app/api/books/7863889b-51ec-49d8-b7ea-2beff3724c3f

### Put new book
PUT http://localhost:9080/library-app/api/books/a2b8423d-6073-4e57-acbc-f195e6263bb0
Content-Type: application/json

{
  "title": "A book",
  "releaseDate": "2020-10-11",
  "genre": "FANTASY",
  "author": "24a84717-c36c-42c1-b69c-c63546d4449d",
  "user": "80ed5ffb-a67a-4253-910c-a64134a01ccf"
}

### Get new book
GET http://localhost:9080/library-app/api/books/a2b8423d-6073-4e57-acbc-f195e6263bb0

### Patch new book
PATCH http://localhost:9080/library-app/api/books/a2b8423d-6073-4e57-acbc-f195e6263bb0
Content-Type: application/json

{
  "title": "A nice book",
  "releaseDate": "2020-10-11",
  "genre": "FANTASY"
}

### Delete book
DELETE http://localhost:9080/library-app/api/books/a2b8423d-6073-4e57-acbc-f195e6263bb0


# PLAYER

### Get all users
GET http://localhost:9080/library-app/api/users

### Get user not exist
GET http://localhost:9080/library-app/api/users/7863889b-51ec-49d8-b7ea-2beff3724c3a

### Get Kacper
GET http://localhost:9080/library-app/api/users/80ed5ffb-a67a-4253-910c-a64134a01ccf

### Put new user
PUT http://localhost:9080/library-app/api/users/a2b8423d-6073-4e57-acbc-f195e6263aa2
Content-Type: application/json

{
  "username": "Konrad",
  "emailAddress": "Konrad@gmail.com"
}

### Get new user
GET http://localhost:9080/library-app/api/users/a2b8423d-6073-4e57-acbc-f195e6263aa2

### Patch new user
PATCH http://localhost:9080/library-app/api/users/a2b8423d-6073-4e57-acbc-f195e6263aa2
Content-Type: application/json

{
  "username": "Konrad",
  "emailAddress": "Konrad@onet.com"
}

### Delete user
DELETE http://localhost:9080/library-app/api/users/a2b8423d-6073-4e57-acbc-f195e6263aa2

### Get user not exist avatar
GET http://localhost:9080/library-app/api/users/80ed5ffb-a67a-4253-910c-a64134a01cca/avatar

### Get Kacper avatar
GET http://localhost:9080/library-app/api/users/80ed5ffb-a67a-4253-910c-a64134a01ccf/avatar

### Put Kacper avatar
PUT http://localhost:9080/library-app/api/users/80ed5ffb-a67a-4253-910c-a64134a01ccf/avatar
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="avatar"; filename="80ed5ffb-a67a-4253-910c-a64134a01ccf.png"
Content-Type: image/png

< ./src/main/resources/avatar/80ed5ffb-a67a-4253-910c-a64134a01ccf.png
--boundary--

### Delete Kacper avatar
DELETE http://localhost:9080/library-app/api/users/80ed5ffb-a67a-4253-910c-a64134a01ccf/avatar