### Get all authors
GET http://localhost:9080/library-app/api/authors

### Get not/existing author
GET http://localhost:9080/library-app/api/authors/04784e3f-0998-4349-9a69-fc3862095f8c

### Put new author
PUT http://localhost:9080/library-app/api/authors/a2b8423d-6073-4e57-acbc-f195e6263bb3
Content-Type: application/json

{
  "name": "Andrzej",
  "nationality": "Polish"
}

### Get new author
GET http://localhost:9080/library-app/api/authors/a2b8423d-6073-4e57-acbc-f195e6263bb3

### Patch new author
PATCH http://localhost:9080/library-app/api/authors/a2b8423d-6073-4e57-acbc-f195e6263bb3
Content-Type: application/json

{
  "name": "Jakub",
  "nationality": "Polish"
}

### Delete author
DELETE http://localhost:9080/library-app/api/authors/782e9182-ae8f-4394-917d-892593fc6547