### Get all users
GET http://localhost:9080/library-app/api/users

### Get not/existing user
GET http://localhost:9080/library-app/api/users/e04137e8-85fe-4241-97b7-e6c2904646cd

### Put new user
PUT http://localhost:9080/library-app/api/users/a2b8423d-6073-4e57-acbc-f195e6263aa2
Content-Type: application/json

{
  "username": "Konrad",
  "login": "Konrad",
  "emailAddress": "Konrad@gmail.com",
  "password": "password"
}

### Get new user
GET http://localhost:9080/library-app/api/users/a2b8423d-6073-4e57-acbc-f195e6263aa2

### Patch new user
PATCH http://localhost:9080/library-app/api/users/a2b8423d-6073-4e57-acbc-f195e6263aa2
Content-Type: application/json

{
  "username": "Konrad",
  "emailAddress": "Konrad@onet.com"
}

### Delete user
DELETE http://localhost:9080/library-app/api/users/a2b8423d-6073-4e57-acbc-f195e6263aa2

### Get existing user avatar
GET http://localhost:9080/library-app/api/users/013828b3-1793-4ca1-817e-d1f1e25140f0/avatar

### Put Kacper avatar
PUT http://localhost:9080/library-app/api/users/013828b3-1793-4ca1-817e-d1f1e25140f0/avatar
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="avatar"; filename="new_Kacper.png"
Content-Type: image/png

< ./src/main/resources/avatar/80ed5ffb-a67a-4253-910c-a64134a01ccf.png
--boundary--

### Delete Kacper avatar
DELETE http://localhost:9080/library-app/api/users/80ed5ffb-a67a-4253-910c-a64134a01ccf/avatar